### ISSUE TITLE
Logging to file is inconsistent 

### ISSUE THREAD

**Issue by GisliGeorgs** [SightPP/Intel_IXN_SightPP#22]
Logging creates the file but nothing gets added to it.

**Comment by lspcool** [comment]
When I run the program, the logging file is created and I can see content in the file.

**Comment by GisliGeorgs** [comment]
Hmm, okay. It's very hit-or-miss for me. I'll explore it some.

**Comment by SvenStruanFinlay** [comment]
Do you guys have access to bug reporting in Jira?
Or just creating issues in general?

**Comment by GisliGeorgs** [comment]
Yes we do.

**Comment by lspcool** [comment]
I cannot see the log in CMake version
